on:
  issue_comment:
    types: [created]

jobs:
  style_command:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup air 
        uses: posit-dev/setup-air@v1

      - name: run air to make changes
        run: air format .

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: specify base branch
      #   id: specify-base
      #   if: ${{ inputs.commit-directly == false }}
      #   run: |
      #     if [ -n ${{ github.head_ref }} ]; then
      #       echo "base=${{github.head_ref}}" >> "$GITHUB_OUTPUT"
      #     elif [ -n ${{ github.ref_name }} ]; then
      #       echo "base=${{github.ref_name}}" >> "$GITHUB_OUTPUT"
      #     else
      #       echo "both github.head_ref and github.ref_name do not exist" >&2
      #       exit 1
      #     fi  
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     commit-message: 'style and docs: run devtools::document() and styler::style_pkg()'
      #     branch: style-doc-code-${{ github.ref_name }}
      #     base: ${{ steps.specify-base.outputs.base }}
      #     title: 'Style code and document'
      #     body: |
      #      Auto-generated by [doc-and-style-r.yml][1]

      #        [1]: https://github.com/nmfs-ost/ghactions4r/tree/main/.github/workflows/doc-and-style-r.yml
