# Reusable workflow to calculate coverage; don't push to code cov.
name: calc-cov-badge

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

permissions: {}

jobs:
  calc-cov-badge:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2, any::htmltools, any::DT
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov, filename = "coverage.xml")
        shell: Rscript {0}
  
      - uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ${{ secrets.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
          ref: true
