on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  style_command:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: ubuntu-latest
    steps:


      # - name: View context attributes (issue number)
      #   uses: actions/github-script@v7
      #   with:
      #     script: console.log(context.issue.number)
      
      # - uses: actions/github-script@v7
      #   id: set-result
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     result-encoding: string
      #     script: |
      #       const pr = github.rest.pulls.get({ 
      #         owner: context.repo.owner,
      #         repo: context.repo.repo, 
      #         pull_number: context.issue.number });
      #       return pr
      
      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.pr}}"
      # - name: View context attributes (headsha)
      #   uses: actions/github-script@v7
      #   with:
      #     script: console.log(steps.set-result.outputs.pr.head.sha)

      - name: checkout (default)
        uses: actions/checkout@v4

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get original PR branch name
        id: get_branch
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=$(basename "$PR_URL")
          BRANCH_NAME=$(gh pr view $PR_NUM --json headRefName -q .headRefName)
          echo "The original PR branch is: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_branch.outputs.branch_name }}
  
      - name: setup air 
        uses: posit-dev/setup-air@v1

      - name: run air to make changes
        run: air format .

      # - name: view values
      #   run: |
      #     echo "headref: $github.head_ref"
      #     echo "refname: $github.ref_name"

      # - name: commit output
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Style with air"

      # - uses: r-lib/actions/pr-push@v2
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      
      # - name: specify base branch
      #   id: specify-base
      #   if: ${{ inputs.commit-directly == false }}
      #   run: |
      #     if [ -n ${{ github.head_ref }} ]; then
      #       echo "base=${{github.head_ref}}" >> "$GITHUB_OUTPUT"
      #     elif [ -n ${{ github.ref_name }} ]; then
      #       echo "base=${{github.ref_name}}" >> "$GITHUB_OUTPUT"
      #     else
      #       echo "both github.head_ref and github.ref_name do not exist" >&2
      #       exit 1
      #     fi  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'style and docs: run devtools::document() and styler::style_pkg()'
          branch: "style-${{ github.run_id }}"
          base: ${{ steps.get_branch.outputs.branch_name }}
          title: 'Style code and document'
          body: |
           Auto-generated by [doc-and-style-r.yml][1]

             [1]: https://github.com/nmfs-ost/ghactions4r/tree/main/.github/workflows/doc-and-style-r.yml